services:
  papra:
    container_name: papra
    image: ghcr.io/papra-hq/papra:latest
    restart: unless-stopped
    ports:
      - "1221:1221"
    environment:
      - APP_BASE_URL=${APP_BASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_IS_REGISTRATION_ENABLED=${AUTH_IS_REGISTRATION_ENABLED}
      - DOCUMENT_STORAGE_DRIVER=${DOCUMENT_STORAGE_DRIVER}
      - EMAILS_DRIVER=${EMAILS_DRIVER}
    volumes:
      - ./app-data:/app/app-data

