services:
  papra:
    container_name: papra
    build:
      context: .
      dockerfile: packages/app/Dockerfile
    restart: unless-stopped
    ports:
      - "1221:1221"
    environment:
      - APP_BASE_URL=${APP_BASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_IS_REGISTRATION_ENABLED=${AUTH_IS_REGISTRATION_ENABLED:-false}
      - DOCUMENT_STORAGE_DRIVER=${DOCUMENT_STORAGE_DRIVER:-filesystem}
      - EMAILS_DRIVER=${EMAILS_DRIVER:-logger}
    volumes:
      - ${PAPRA_DATA_DIR:-./app-data}:/app/app-data

